### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [isitLoVe/BigWigsVG#20]
I'm getting this error:
Error:  `=' expected near `..'
AddOn: BigWigsVG
File: CThunGroups.lua
Line: 73
Count: 1

Line 73 is the following:
					BigWigsCThunGroups_Group..groupnr[i] = {}

**Comment by isitLoVe** [comment]
Cthun groups is not finished yet u guess i remove it

**Comment by isitLoVe** [comment]
Idea was to make automatic groups for cthun

**Comment by isitLoVe** [comment]
i removed the reference to the lua file until i have it fixed (maybe never ever)
